name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build/Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      matrix:
        go-version: [1.19.10, 1.20.5]
        os: [ubuntu-latest]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... --timeout 60s

    - name: Cross test for i386
      run: env GOOS=linux GOARCH=386 go test -v ./... --timeout 60s

    - name: Cross compile for arm (RPI)
      run: env GOOS=linux GOARCH=arm GOARM=5 go build -v ./...
